import React, { useState, useEffect } from "react";

function PublicTransport() {
    const [alert, setAlert] = useState(null);
    const [announcements, setAnnouncements] = useState([]);
    const [simulatedTime, setSimulatedTime] = useState(new Date());
    const [feedback, setFeedback] = useState("");
    const [feedbackStatus, setFeedbackStatus] = useState("");
    const [busScheduleData] = useState([
        {
            "Schedule No": "Schedule No",
            Route: "Route",
            "Route Type": "Route Type",
            "Travel Distance": "Travel Distance",
            "Travel Time": "Travel Time",
            "Trip Start": "Trip Start",
            "Trip End": "Trip End",
            "Bus Number": "Bus Number",
        },
        {
            "Schedule No": "1/1",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "14:45",
            "Trip End": "15:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/1",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:30",
            "Trip End": "16:10",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/1",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:15",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/1",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:00",
            "Trip End": "17:40",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/1",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:45",
            "Trip End": "18:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/1",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:30",
            "Trip End": "19:10",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/1",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "19:20",
            "Trip End": "20:00",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/1",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "20:05",
            "Trip End": "20:45",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "1/2",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:30",
            "Trip End": "16:10",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "14:15",
            "Trip End": "14:55",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:45",
            "Trip End": "16:25",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:30",
            "Trip End": "17:10",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:15",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:00",
            "Trip End": "18:40",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:45",
            "Trip End": "19:25",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "19:40",
            "Trip End": "20:20",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/2",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "20:25",
            "Trip End": "21:05",
            "Bus Number": "GJ-18-AZ-4946",
        },
        {
            "Schedule No": "1/3",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "14:25",
            "Trip End": "15:05",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:10",
            "Trip End": "15:50",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:55",
            "Trip End": "16:35",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:40",
            "Trip End": "17:20",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:25",
            "Trip End": "18:05",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:10",
            "Trip End": "18:50",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:55",
            "Trip End": "19:35",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "20:00",
            "Trip End": "20:40",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/3",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "20:45",
            "Trip End": "21:25",
            "Bus Number": "GJ-18-AZ-4501",
        },
        {
            "Schedule No": "1/4",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "14:35",
            "Trip End": "15:15",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:20",
            "Trip End": "16:00",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:05",
            "Trip End": "16:45",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:50",
            "Trip End": "17:30",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:35",
            "Trip End": "18:15",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:20",
            "Trip End": "19:00",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "19:05",
            "Trip End": "19:45",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "20:20",
            "Trip End": "21:00",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/4",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "21:05",
            "Trip End": "21:45",
            "Bus Number": "GJ-18-AZ-4815",
        },
        {
            "Schedule No": "1/5",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "14:45",
            "Trip End": "15:25",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:20",
            "Trip End": "16:00",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:15",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:50",
            "Trip End": "17:30",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:45",
            "Trip End": "18:25",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:30",
            "Trip End": "19:10",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "19:15",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "21:25",
            "Trip End": "22:05",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/5",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "20:40",
            "Trip End": "21:20",
            "Bus Number": "GJ-18-AZ-5707",
        },
        {
            "Schedule No": "1/6",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:45",
            "Trip End": "16:25",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "14:15",
            "Trip End": "14:55",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:00",
            "Trip End": "15:40",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:30",
            "Trip End": "17:10",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:15",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:00",
            "Trip End": "18:40",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:45",
            "Trip End": "19:25",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "19:30",
            "Trip End": "20:10",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "21:00",
            "Trip End": "21:40",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/6",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "21:45",
            "Trip End": "22:25",
            "Bus Number": "GJ-18-AZ-5101",
        },
        {
            "Schedule No": "1/7",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "14:30",
            "Trip End": "15:10",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "15:15",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:00",
            "Trip End": "16:40",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "16:45",
            "Trip End": "17:25",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "17:30",
            "Trip End": "18:10",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "18:15",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "19:00",
            "Trip End": "19:40",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "19:45",
            "Trip End": "20:25",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Pathika To Chandkheda",
            "Route Type": "Up",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "21:30",
            "Trip End": "22:10",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "1/7",
            Route: "Chandkheda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "16",
            "Travel Time": "00:40",
            "Trip Start": "22:15",
            "Trip End": "22:55",
            "Bus Number": "GJ-18-AZ-4870",
        },
        {
            "Schedule No": "2/1",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "14:20",
            "Trip End": "15:15",
            "Bus Number": "GJ-18-AZ-5534",
        },
        {
            "Schedule No": "2/1",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "15:20",
            "Trip End": "16:15",
            "Bus Number": "GJ-18-AZ-5534",
        },
        {
            "Schedule No": "2/1",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "16:20",
            "Trip End": "17:15",
            "Bus Number": "GJ-18-AZ-5534",
        },
        {
            "Schedule No": "2/1",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "17:20",
            "Trip End": "18:15",
            "Bus Number": "GJ-18-AZ-5534",
        },
        {
            "Schedule No": "2/1",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "18:20",
            "Trip End": "19:15",
            "Bus Number": "GJ-18-AZ-5534",
        },
        {
            "Schedule No": "2/1",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "19:20",
            "Trip End": "20:15",
            "Bus Number": "GJ-18-AZ-5534",
        },
        {
            "Schedule No": "2/1",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "20:20",
            "Trip End": "21:15",
            "Bus Number": "GJ-18-AZ-5534",
        },
        {
            "Schedule No": "2/2",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "14:40",
            "Trip End": "15:35",
            "Bus Number": "GJ-18-AZ-4681",
        },
        {
            "Schedule No": "2/2",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "15:40",
            "Trip End": "16:35",
            "Bus Number": "GJ-18-AZ-4681",
        },
        {
            "Schedule No": "2/2",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "16:40",
            "Trip End": "17:35",
            "Bus Number": "GJ-18-AZ-4681",
        },
        {
            "Schedule No": "2/2",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "17:40",
            "Trip End": "18:35",
            "Bus Number": "GJ-18-AZ-4681",
        },
        {
            "Schedule No": "2/2",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "18:40",
            "Trip End": "19:35",
            "Bus Number": "GJ-18-AZ-4681",
        },
        {
            "Schedule No": "2/2",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "19:40",
            "Trip End": "20:35",
            "Bus Number": "GJ-18-AZ-4681",
        },
        {
            "Schedule No": "2/2",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "20:40",
            "Trip End": "21:35",
            "Bus Number": "GJ-18-AZ-4681",
        },
        {
            "Schedule No": "2/3",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "15:00",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-4907",
        },
        {
            "Schedule No": "2/3",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "16:00",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-4907",
        },
        {
            "Schedule No": "2/3",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "17:00",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4907",
        },
        {
            "Schedule No": "2/3",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "18:00",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-4907",
        },
        {
            "Schedule No": "2/3",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "19:00",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-4907",
        },
        {
            "Schedule No": "2/3",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "20:00",
            "Trip End": "20:55",
            "Bus Number": "GJ-18-AZ-4907",
        },
        {
            "Schedule No": "2/3",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "21:00",
            "Trip End": "21:55",
            "Bus Number": "GJ-18-AZ-4907",
        },
        {
            "Schedule No": "2/4",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "14:20",
            "Trip End": "15:15",
            "Bus Number": "GJ-18-AZ-4929",
        },
        {
            "Schedule No": "2/4",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "15:20",
            "Trip End": "16:15",
            "Bus Number": "GJ-18-AZ-4929",
        },
        {
            "Schedule No": "2/4",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "16:20",
            "Trip End": "17:15",
            "Bus Number": "GJ-18-AZ-4929",
        },
        {
            "Schedule No": "2/4",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "17:20",
            "Trip End": "18:15",
            "Bus Number": "GJ-18-AZ-4929",
        },
        {
            "Schedule No": "2/4",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "18:20",
            "Trip End": "19:15",
            "Bus Number": "GJ-18-AZ-4929",
        },
        {
            "Schedule No": "2/4",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "19:20",
            "Trip End": "20:15",
            "Bus Number": "GJ-18-AZ-4929",
        },
        {
            "Schedule No": "2/5",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "14:40",
            "Trip End": "15:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/5",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "15:40",
            "Trip End": "16:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/5",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "16:40",
            "Trip End": "17:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/5",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "17:40",
            "Trip End": "18:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/5",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "18:40",
            "Trip End": "19:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/5",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "19:40",
            "Trip End": "20:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/5",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "20:40",
            "Trip End": "21:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/5",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "21:40",
            "Trip End": "22:35",
            "Bus Number": "GJ-18-AZ-4963",
        },
        {
            "Schedule No": "2/6",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "15:00",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-4757",
        },
        {
            "Schedule No": "2/6",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "16:00",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-4757",
        },
        {
            "Schedule No": "2/6",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "17:00",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4757",
        },
        {
            "Schedule No": "2/6",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "18:00",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-4757",
        },
        {
            "Schedule No": "2/6",
            Route: "Pathika To Unava",
            "Route Type": "Up",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "19:00",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-4757",
        },
        {
            "Schedule No": "2/6",
            Route: "Unava To Pathika",
            "Route Type": "Down",
            "Travel Distance": "18",
            "Travel Time": "00:55",
            "Trip Start": "20:00",
            "Trip End": "20:55",
            "Bus Number": "GJ-18-AZ-4757",
        },
        {
            "Schedule No": "3/1",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "15:00",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-4734",
        },
        {
            "Schedule No": "3/1",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "16:00",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-4734",
        },
        {
            "Schedule No": "3/1",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "17:00",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4734",
        },
        {
            "Schedule No": "3/1",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "18:00",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-4734",
        },
        {
            "Schedule No": "3/1",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "19:00",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-4734",
        },
        {
            "Schedule No": "3/2",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "14:20",
            "Trip End": "15:15",
            "Bus Number": "GJ-18-AZ-4831",
        },
        {
            "Schedule No": "3/2",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "15:20",
            "Trip End": "16:15",
            "Bus Number": "GJ-18-AZ-4831",
        },
        {
            "Schedule No": "3/2",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "16:20",
            "Trip End": "17:15",
            "Bus Number": "GJ-18-AZ-4831",
        },
        {
            "Schedule No": "3/2",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "17:20",
            "Trip End": "18:15",
            "Bus Number": "GJ-18-AZ-4831",
        },
        {
            "Schedule No": "3/2",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "18:20",
            "Trip End": "19:15",
            "Bus Number": "GJ-18-AZ-4831",
        },
        {
            "Schedule No": "3/2",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "19:20",
            "Trip End": "20:15",
            "Bus Number": "GJ-18-AZ-4831",
        },
        {
            "Schedule No": "3/3",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "14:40",
            "Trip End": "15:35",
            "Bus Number": "GJ-18-AZ-4616",
        },
        {
            "Schedule No": "3/3",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "15:40",
            "Trip End": "16:35",
            "Bus Number": "GJ-18-AZ-4616",
        },
        {
            "Schedule No": "3/3",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "16:40",
            "Trip End": "17:35",
            "Bus Number": "GJ-18-AZ-4616",
        },
        {
            "Schedule No": "3/3",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "17:40",
            "Trip End": "18:35",
            "Bus Number": "GJ-18-AZ-4616",
        },
        {
            "Schedule No": "3/3",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "18:40",
            "Trip End": "19:35",
            "Bus Number": "GJ-18-AZ-4616",
        },
        {
            "Schedule No": "3/3",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "19:40",
            "Trip End": "20:35",
            "Bus Number": "GJ-18-AZ-4616",
        },
        {
            "Schedule No": "3/4",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "20:00",
            "Trip End": "20:55",
            "Bus Number": "GJ-18-AZ-4596",
        },
        {
            "Schedule No": "3/4",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "15:00",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-4596",
        },
        {
            "Schedule No": "3/4",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "16:00",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-4596",
        },
        {
            "Schedule No": "3/4",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "17:00",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4596",
        },
        {
            "Schedule No": "3/4",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "18:00",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-4596",
        },
        {
            "Schedule No": "3/4",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "19:00",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-4596",
        },
        {
            "Schedule No": "3/5",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "14:20",
            "Trip End": "15:15",
            "Bus Number": "GJ-18-AZ-6448",
        },
        {
            "Schedule No": "3/5",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "15:20",
            "Trip End": "16:15",
            "Bus Number": "GJ-18-AZ-6448",
        },
        {
            "Schedule No": "3/5",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "16:20",
            "Trip End": "17:15",
            "Bus Number": "GJ-18-AZ-6448",
        },
        {
            "Schedule No": "3/5",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "17:20",
            "Trip End": "18:15",
            "Bus Number": "GJ-18-AZ-6448",
        },
        {
            "Schedule No": "3/5",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "18:20",
            "Trip End": "19:15",
            "Bus Number": "GJ-18-AZ-6448",
        },
        {
            "Schedule No": "3/5",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "19:20",
            "Trip End": "20:15",
            "Bus Number": "GJ-18-AZ-6448",
        },
        {
            "Schedule No": "3/5",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "20:20",
            "Trip End": "21:15",
            "Bus Number": "GJ-18-AZ-6448",
        },
        {
            "Schedule No": "3/6",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "14:40",
            "Trip End": "15:35",
            "Bus Number": "GJ-18-AZ-6127",
        },
        {
            "Schedule No": "3/6",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "15:40",
            "Trip End": "16:35",
            "Bus Number": "GJ-18-AZ-6127",
        },
        {
            "Schedule No": "3/6",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "16:40",
            "Trip End": "17:35",
            "Bus Number": "GJ-18-AZ-6127",
        },
        {
            "Schedule No": "3/6",
            Route: "Pathika To Indira Bridge",
            "Route Type": "Up",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "17:40",
            "Trip End": "18:35",
            "Bus Number": "GJ-18-AZ-6127",
        },
        {
            "Schedule No": "3/6",
            Route: "Indira Bridge To Pathika",
            "Route Type": "Down",
            "Travel Distance": "15",
            "Travel Time": "00:55",
            "Trip Start": "18:40",
            "Trip End": "19:35",
            "Bus Number": "GJ-18-AZ-6127",
        },
        {
            "Schedule No": "4/1",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "14:30",
            "Trip End": "15:25",
            "Bus Number": "GJ-18-AZ-4890",
        },
        {
            "Schedule No": "4/1",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "15:30",
            "Trip End": "16:25",
            "Bus Number": "GJ-18-AZ-4890",
        },
        {
            "Schedule No": "4/1",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "16:30",
            "Trip End": "17:25",
            "Bus Number": "GJ-18-AZ-4890",
        },
        {
            "Schedule No": "4/1",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "17:30",
            "Trip End": "18:25",
            "Bus Number": "GJ-18-AZ-4890",
        },
        {
            "Schedule No": "4/1",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "18:30",
            "Trip End": "19:25",
            "Bus Number": "GJ-18-AZ-4890",
        },
        {
            "Schedule No": "4/2",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "15:00",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-5612",
        },
        {
            "Schedule No": "4/2",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "16:00",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-5612",
        },
        {
            "Schedule No": "4/2",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "17:00",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-5612",
        },
        {
            "Schedule No": "4/2",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "18:00",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-5612",
        },
        {
            "Schedule No": "4/2",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "19:00",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-5612",
        },
        {
            "Schedule No": "4/3",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "14:30",
            "Trip End": "15:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "4/3",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "15:30",
            "Trip End": "16:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "4/3",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "16:30",
            "Trip End": "17:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "4/3",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "17:30",
            "Trip End": "18:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "4/3",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "18:30",
            "Trip End": "19:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "4/3",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "19:30",
            "Trip End": "20:25",
            "Bus Number": "GJ-18-AZ-6192",
        },
        {
            "Schedule No": "4/4",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "15:00",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-6445",
        },
        {
            "Schedule No": "4/4",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "16:00",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-6445",
        },
        {
            "Schedule No": "4/4",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "17:00",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-6445",
        },
        {
            "Schedule No": "4/4",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "18:00",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-6445",
        },
        {
            "Schedule No": "4/4",
            Route: "Pathika To Dhamasana",
            "Route Type": "Up",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "19:00",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-6445",
        },
        {
            "Schedule No": "4/4",
            Route: "Dhamasana To Pathika",
            "Route Type": "Down",
            "Travel Distance": "19.4",
            "Travel Time": "00:55",
            "Trip Start": "20:00",
            "Trip End": "20:55",
            "Bus Number": "GJ-18-AZ-6445",
        },
        {
            "Schedule No": "5/1",
            Route: "Uvarsad To Pathika",
            "Route Type": "Down",
            "Travel Distance": "9",
            "Travel Time": "00:40",
            "Trip Start": "14:15",
            "Trip End": "14:55",
            "Bus Number": "GJ-18-AZ-4559",
        },
        {
            "Schedule No": "5/1",
            Route: "Pathika To Uvarsad",
            "Route Type": "Up",
            "Travel Distance": "9",
            "Travel Time": "00:40",
            "Trip Start": "15:00",
            "Trip End": "15:40",
            "Bus Number": "GJ-18-AZ-4559",
        },
        {
            "Schedule No": "5/1",
            Route: "Uvarsad To Pathika",
            "Route Type": "Down",
            "Travel Distance": "9",
            "Travel Time": "00:40",
            "Trip Start": "15:45",
            "Trip End": "16:25",
            "Bus Number": "GJ-18-AZ-4559",
        },
        {
            "Schedule No": "5/1",
            Route: "Pathika To Uvarsad",
            "Route Type": "Up",
            "Travel Distance": "9",
            "Travel Time": "00:40",
            "Trip Start": "16:30",
            "Trip End": "17:10",
            "Bus Number": "GJ-18-AZ-4559",
        },
        {
            "Schedule No": "5/1",
            Route: "Uvarsad To Pathika",
            "Route Type": "Down",
            "Travel Distance": "9",
            "Travel Time": "00:40",
            "Trip Start": "17:15",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4559",
        },
        {
            "Schedule No": "5/1",
            Route: "Pathika To Uvarsad",
            "Route Type": "Up",
            "Travel Distance": "9",
            "Travel Time": "00:40",
            "Trip Start": "18:30",
            "Trip End": "19:10",
            "Bus Number": "GJ-18-AZ-4559",
        },
        {
            "Schedule No": "5/1",
            Route: "Uvarsad To Pathika",
            "Route Type": "Down",
            "Travel Distance": "9",
            "Travel Time": "00:40",
            "Trip Start": "19:15",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-4559",
        },
        {
            "Schedule No": "6/1",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "14:15",
            "Trip End": "14:40",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "14:45",
            "Trip End": "15:10",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "15:15",
            "Trip End": "15:40",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "15:45",
            "Trip End": "16:10",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "16:15",
            "Trip End": "16:40",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "16:45",
            "Trip End": "17:10",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "17:15",
            "Trip End": "17:40",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "17:45",
            "Trip End": "18:10",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "18:15",
            "Trip End": "18:40",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "18:45",
            "Trip End": "19:10",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "19:15",
            "Trip End": "19:40",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "19:45",
            "Trip End": "20:10",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/1",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "20:15",
            "Trip End": "20:40",
            "Bus Number": "GJ-18-AZ-4568",
        },
        {
            "Schedule No": "6/2",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "14:15",
            "Trip End": "14:40",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "14:45",
            "Trip End": "15:10",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "15:15",
            "Trip End": "15:40",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "15:45",
            "Trip End": "16:10",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "16:15",
            "Trip End": "16:40",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "16:45",
            "Trip End": "17:10",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "17:15",
            "Trip End": "17:40",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "17:45",
            "Trip End": "18:10",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "18:15",
            "Trip End": "18:40",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "18:45",
            "Trip End": "19:10",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "19:15",
            "Trip End": "19:40",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "19:45",
            "Trip End": "20:10",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pathika To Pethapur",
            "Route Type": "Up",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "20:15",
            "Trip End": "20:40",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "6/2",
            Route: "Pethapur To Pathika",
            "Route Type": "Down",
            "Travel Distance": "8",
            "Travel Time": "00:25",
            "Trip Start": "20:45",
            "Trip End": "21:10",
            "Bus Number": "GJ-18-AZ-4521",
        },
        {
            "Schedule No": "7/1",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "14:45",
            "Trip End": "15:25",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/1",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:30",
            "Trip End": "16:10",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/1",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:15",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/1",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:00",
            "Trip End": "17:40",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/1",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:45",
            "Trip End": "18:25",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/1",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:30",
            "Trip End": "19:10",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/1",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "19:20",
            "Trip End": "20:00",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/1",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "20:05",
            "Trip End": "20:45",
            "Bus Number": "GJ-18-AZ-4769",
        },
        {
            "Schedule No": "7/2",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:00",
            "Trip End": "15:40",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "14:15",
            "Trip End": "14:55",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:45",
            "Trip End": "16:25",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:30",
            "Trip End": "17:10",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:15",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:00",
            "Trip End": "18:40",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:45",
            "Trip End": "19:25",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "19:40",
            "Trip End": "20:20",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/2",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "20:25",
            "Trip End": "21:05",
            "Bus Number": "GJ-18-AZ-4738",
        },
        {
            "Schedule No": "7/3",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "14:30",
            "Trip End": "15:10",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:15",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:00",
            "Trip End": "16:40",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:45",
            "Trip End": "17:25",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:30",
            "Trip End": "18:10",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:15",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "19:00",
            "Trip End": "19:40",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "20:00",
            "Trip End": "20:40",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/3",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "20:45",
            "Trip End": "21:25",
            "Bus Number": "GJ-18-AZ-4982",
        },
        {
            "Schedule No": "7/4",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "14:45",
            "Trip End": "15:25",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:30",
            "Trip End": "16:10",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:15",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:00",
            "Trip End": "17:40",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:45",
            "Trip End": "18:25",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:30",
            "Trip End": "19:10",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "19:15",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "20:20",
            "Trip End": "21:00",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/4",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "21:05",
            "Trip End": "21:45",
            "Bus Number": "GJ-18-AZ-4917",
        },
        {
            "Schedule No": "7/5",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "14:15",
            "Trip End": "14:55",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:00",
            "Trip End": "15:40",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:45",
            "Trip End": "16:25",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:30",
            "Trip End": "17:10",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:15",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:00",
            "Trip End": "18:40",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:45",
            "Trip End": "19:25",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "19:30",
            "Trip End": "20:10",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "20:40",
            "Trip End": "21:20",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/5",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "21:25",
            "Trip End": "22:05",
            "Bus Number": "GJ-18-AZ-4985",
        },
        {
            "Schedule No": "7/6",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "14:30",
            "Trip End": "15:10",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:00",
            "Trip End": "16:40",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "21:30",
            "Trip End": "22:10",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "22:15",
            "Trip End": "22:55",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "15:15",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "16:45",
            "Trip End": "17:25",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "17:30",
            "Trip End": "18:10",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "18:15",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Pathika To Chiloda",
            "Route Type": "Up",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "19:00",
            "Trip End": "19:40",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "7/6",
            Route: "Chiloda To Pathika",
            "Route Type": "Down",
            "Travel Distance": "13",
            "Travel Time": "00:40",
            "Trip Start": "19:45",
            "Trip End": "20:25",
            "Bus Number": "GJ-18-AZ-4733",
        },
        {
            "Schedule No": "8/1",
            Route: "Pathika To Vasna (Patiya)",
            "Route Type": "Up",
            "Travel Distance": "21.7",
            "Travel Time": "00:55",
            "Trip Start": "18:00",
            "Trip End": "18:55",
            "Bus Number": "GJ-18-AZ-5828",
        },
        {
            "Schedule No": "8/1",
            Route: "Vasna (Patiya) To Pathika",
            "Route Type": "Down",
            "Travel Distance": "21.7",
            "Travel Time": "00:55",
            "Trip Start": "15:00",
            "Trip End": "15:55",
            "Bus Number": "GJ-18-AZ-5828",
        },
        {
            "Schedule No": "8/1",
            Route: "Pathika To Vasna (Patiya)",
            "Route Type": "Up",
            "Travel Distance": "21.7",
            "Travel Time": "00:55",
            "Trip Start": "16:00",
            "Trip End": "16:55",
            "Bus Number": "GJ-18-AZ-5828",
        },
        {
            "Schedule No": "8/1",
            Route: "Vasna (Patiya) To Pathika",
            "Route Type": "Down",
            "Travel Distance": "21.7",
            "Travel Time": "00:55",
            "Trip Start": "17:00",
            "Trip End": "17:55",
            "Bus Number": "GJ-18-AZ-5828",
        },
        {
            "Schedule No": "8/1",
            Route: "Vasna (Patiya) To Pathika",
            "Route Type": "Down",
            "Travel Distance": "21.7",
            "Travel Time": "00:55",
            "Trip Start": "19:00",
            "Trip End": "19:55",
            "Bus Number": "GJ-18-AZ-5828",
        },
        {
            "Schedule No": "9/1",
            Route: "Pathika To Sadra",
            "Route Type": "Up",
            "Travel Distance": "26.2",
            "Travel Time": "00:58",
            "Trip Start": "15:00",
            "Trip End": "15:58",
            "Bus Number": "GJ-18-AZ-5939",
        },
        {
            "Schedule No": "9/1",
            Route: "Sadra To Pathika",
            "Route Type": "Down",
            "Travel Distance": "26.2",
            "Travel Time": "00:58",
            "Trip Start": "16:00",
            "Trip End": "16:58",
            "Bus Number": "GJ-18-AZ-5939",
        },
        {
            "Schedule No": "9/1",
            Route: "Pathika To Sadra",
            "Route Type": "Up",
            "Travel Distance": "26.2",
            "Travel Time": "00:58",
            "Trip Start": "17:00",
            "Trip End": "17:58",
            "Bus Number": "GJ-18-AZ-5939",
        },
        {
            "Schedule No": "9/1",
            Route: "Sadra To Pathika",
            "Route Type": "Down",
            "Travel Distance": "26.2",
            "Travel Time": "00:58",
            "Trip Start": "18:00",
            "Trip End": "18:58",
            "Bus Number": "GJ-18-AZ-5939",
        },
        {
            "Schedule No": "9/1",
            Route: "Pathika To Sadra",
            "Route Type": "Up",
            "Travel Distance": "26.2",
            "Travel Time": "00:58",
            "Trip Start": "19:00",
            "Trip End": "19:58",
            "Bus Number": "GJ-18-AZ-5939",
        },
        {
            "Schedule No": "9/1",
            Route: "Sadra To Pathika",
            "Route Type": "Down",
            "Travel Distance": "26.2",
            "Travel Time": "00:58",
            "Trip Start": "20:00",
            "Trip End": "20:58",
            "Bus Number": "GJ-18-AZ-5939",
        },
    ]);

    // Simulate fetching service alert
    useEffect(() => {
        const alertTimer = setTimeout(() => {
            setAlert({
                message:
                    "Maintenance work on Bus Route 5 may cause delays today.",
            });
        }, 2000);
        return () => clearTimeout(alertTimer);
    }, []);

    // Simulate fetching announcements
    useEffect(() => {
        const announcementsTimer = setTimeout(() => {
            setAnnouncements([
                "Metro service extended hours on weekends.",
                "New dedicated bike lanes launched downtown.",
                "Road construction on Main St. – alternative routes recommended.",
            ]);
        }, 1000);
        return () => clearTimeout(announcementsTimer);
    }, []);

    // Update simulated time every minute
    useEffect(() => {
        const timer = setInterval(() => {
            setSimulatedTime(new Date());
        }, 60000);
        return () => clearInterval(timer);
    }, []);

    const handleFeedbackSubmit = (e) => {
        e.preventDefault();
        console.log("User Feedback:", feedback);
        setFeedbackStatus("Thank you for your feedback!");
        setFeedback("");
        setTimeout(() => setFeedbackStatus(""), 3000);
    };

    return (
        <div className="max-w-5xl mx-auto p-6 space-y-8">
            <h2 className="text-3xl font-bold mb-4">Public Transport</h2>
            <p className="text-lg">
                Access and manage public transportation schedules, updates, and
                tips.
            </p>

            {/* Service Alerts */}
            {alert && (
                <section className="bg-yellow-100 border-l-4 border-yellow-500 p-4">
                    <p className="text-yellow-700 font-semibold">
                        Service Alert: {alert.message}
                    </p>
                </section>
            )}

            {/* Overview */}
            <section className="space-y-4">
                <h3 className="text-2xl font-semibold">Overview</h3>
                <p className="text-gray-700">
                    Our public transport system is the lifeline of the city,
                    offering a network of buses, trams, and metro services to
                    ensure efficient and sustainable mobility.
                </p>
            </section>

            {/* Announcements */}
            <section className="space-y-4">
                <h3 className="text-2xl font-semibold">Latest Announcements</h3>
                {announcements.length === 0 ? (
                    <p>Loading announcements...</p>
                ) : (
                    <ul className="list-disc ml-5 text-gray-700">
                        {announcements.map((item, index) => (
                            <li key={index}>{item}</li>
                        ))}
                    </ul>
                )}
            </section>

            {/* ✅ Bus Schedule Table Section */}
            <section className="space-y-4">
                <h3 className="text-2xl font-semibold">
                    Bus Routes & Schedules
                </h3>
                <p className="text-gray-700">Below are the bus schedules:</p>
                <div className="overflow-x-auto">
                    <table className="min-w-full table-auto border border-gray-300 text-sm">
                        <thead className="bg-gray-200">
                            <tr>
                                <th className="border px-2 py-1">
                                    Schedule No
                                </th>
                                <th className="border px-2 py-1">Route</th>
                                <th className="border px-2 py-1">Route Type</th>
                                <th className="border px-2 py-1">
                                    Distance (km)
                                </th>
                                <th className="border px-2 py-1">
                                    Travel Time
                                </th>
                                <th className="border px-2 py-1">Trip Start</th>
                                <th className="border px-2 py-1">Trip End</th>
                                <th className="border px-2 py-1">Bus Number</th>
                            </tr>
                        </thead>
                        <tbody>
                            {busScheduleData.map((bus, idx) => (
                                <tr
                                    key={idx}
                                    className="odd:bg-white even:bg-gray-100"
                                >
                                    <td className="border px-2 py-1">
                                        {bus["Schedule No"]}
                                    </td>
                                    <td className="border px-2 py-1">
                                        {bus["Route"]}
                                    </td>
                                    <td className="border px-2 py-1">
                                        {bus["Route Type"]}
                                    </td>
                                    <td className="border px-2 py-1">
                                        {bus["Travel Distance"]}
                                    </td>
                                    <td className="border px-2 py-1">
                                        {bus["Travel Time"]}
                                    </td>
                                    <td className="border px-2 py-1">
                                        {bus["Trip Start"]}
                                    </td>
                                    <td className="border px-2 py-1">
                                        {bus["Trip End"]}
                                    </td>
                                    <td className="border px-2 py-1">
                                        {bus["Bus Number"]}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </section>

            {/* Metro Services */}
            <section className="space-y-4">
                <h3 className="text-2xl font-semibold">Metro Services</h3>
                <p className="text-gray-700">
                    Discover our efficient metro services that connect key areas
                    of the city.
                </p>
                <img
                    src="https://themetrorailguy.com/wp-content/uploads/2020/07/AhmedabadMetroPhase2MapN.png"
                    alt="Metro and Tram Map"
                    className="max-w-full h-auto rounded shadow"
                />
            </section>

            {/* Travel Tips */}
            <section className="space-y-4">
                <h3 className="text-2xl font-semibold">Travel Tips</h3>
                <ul className="list-disc ml-5 text-gray-700">
                    <li>
                        Plan your route in advance using local transit
                        schedules.
                    </li>
                    <li>Consider off-peak hours to avoid congestion.</li>
                    <li>Keep an eye on service alerts and announcements.</li>
                    <li>
                        Carry a reusable water bottle and wear comfortable
                        shoes.
                    </li>
                </ul>
            </section>

            {/* Real-Time Updates */}
            <section className="space-y-4">
                <h3 className="text-2xl font-semibold">Real-Time Updates</h3>
                <p className="text-gray-700">
                    Current simulated time: {simulatedTime.toLocaleTimeString()}
                </p>
            </section>

            {/* Traffic View */}
            <section className="space-y-6">
                <h3 className="text-2xl font-bold">Traffic View</h3>
                <p className="text-gray-700">
                    View current traffic conditions in Gandhinagar.
                </p>
                <div className="w-full h-64 rounded-lg overflow-hidden shadow">
                    <iframe
                        title="Traffic Map"
                        src="https://maps.google.com/maps?q=Gandhinagar,Gujarat&output=embed"
                        width="100%"
                        height="100%"
                        style={{ border: 0 }}
                        loading="lazy"
                        allowFullScreen
                    ></iframe>
                </div>
            </section>

            {/* Feedback Form */}
            <section className="space-y-4">
                <h3 className="text-2xl font-semibold">Contact Us</h3>
                <p className="text-gray-700">
                    Have feedback or need assistance? Let us know:
                </p>
                <form onSubmit={handleFeedbackSubmit} className="space-y-2">
                    <textarea
                        value={feedback}
                        onChange={(e) => setFeedback(e.target.value)}
                        placeholder="Enter your feedback"
                        className="w-full p-2 border border-gray-300 rounded"
                        rows="3"
                    ></textarea>
                    <button
                        type="submit"
                        className="px-4 py-2 bg-blue-600 text-white rounded"
                    >
                        Submit Feedback
                    </button>
                </form>
                {feedbackStatus && (
                    <p className="text-green-700 font-semibold">
                        {feedbackStatus}
                    </p>
                )}
            </section>
        </div>
    );
}

export default PublicTransport;
